spring:
   h2:
      console:
         enabled: true
         path: /h2
   datasource:
      url: jdbc:h2:mem:moviesbattle
      username: admin
      password: admin
      driverClassName: org.h2.Driver
   jpa:
      show-sql: false
      spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
   hibernate:
      format_sql: true
   flyway:
      locations: classpath:db/migration,classpath:db/testdata
omdb:
   api:
      host: http://www.omdbapi.com
      key: 9b7950e7